# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20160823_0255'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='block',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='所属版块'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章标题'),
        ),
    ]
